export const keywords = [
  "desembarco",
  "transformando el ecosistema digital",
  "uruguay",
  "uruguaya",
  "uruguayo",
  "valoramos tu tiempo",
  "separando la señal del ruido",
  "comunidad",
  "independiente",
  "información",
  "crítica",
  "realidad uruguaya",
  "contenido digital",
  "creador de contenido",
  "creadores de contenido",
  "humor",
  "dinamismo",
  "datos",
  "plataforma digital",
  "medio de comunicación",
  "comunicación",
  "medios",
  "noticias",
  "resumen semanal",
  "campaña del miedo",
  "miedo al lunes",
  "miedo a los fallos",
  "newsletter",
  "bunkerland",
  "elecciones internas",
  "elecciones internas 2024",
  "resultados elecciones",
  "resultados elecciones internas",
];
