export const keywords = [
  "comunicación",
  "comunidad",
  "contenido digital",
  "creador de contenido",
  "creadores de contenido",
  "crítica",
  "datos",
  "dco",
  "desembarco",
  "dinamismo",
  "humor",
  "independiente",
  "información",
  "medio de comunicación",
  "medio digital",
  "medios",
  "miedo a los fallos",
  "miedo al lunes",
  "newsletter",
  "no somos neutrales",
  "noticias",
  "plataforma digital",
  "realidad uruguaya",
  "resumen semanal",
  "separando la señal del ruido",
  "somos artiguistas",
  "transformando el ecosistema digital",
  "uruguay",
  "uruguaya",
  "uruguayo",
  "valoramos tu tiempo",
];
